name: Compile & Sign launcher.m

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Xcode 26.0.1
      run: |
        curl -O https://download.developer.apple.com/Developer_Tools/Xcode_26.0.1/Xcode_26.0.1.xip
        xip -x Xcode_26.0.1.xip
        sudo mv Xcode_26.0.1.app /Applications/

    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_26.0.1.app/Contents/Developer

    - name: Install certificate
      run: |
        security create-keychain -p "" build.keychain
        security import sign/cert.p12 -k build.keychain -P ${{ secrets.P12_PASSWORD }} -T /usr/bin/codesign
        security list-keychains -s build.keychain
        security unlock-keychain -p "" build.keychain

    - name: Copy provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp sign/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Compile launcher.m
      run: |
        IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
        clang -arch arm64 -isysroot "$IOS_SDK" -framework UIKit -framework Foundation -o C/launcher C/launcher.m
        chmod +x C/launcher

    - name: Code Sign launcher
      run: |
        CODESIGN_IDENTITY="iPhone Developer: Your Name (TEAMID)"
        codesign -f -s "$CODESIGN_IDENTITY" --entitlements sign/entitlements.plist C/launcher