name: Build & Sign

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile mobile.m
        run: |
          mkdir -p build
          clang -framework Foundation C/mobile.m -o build/mobile

      - name: Verify signature
        run: codesign -dv --verbose=4 build/mobile
